import type { Param, ParamId, ParamSet, PresetId } from './tipos'

/**
 * Catalogo de parametros da cana-de-acucar.
 *
 * Todo numero que o site exibe sai daqui ou de uma multiplicacao destes.
 * Nenhum valor fica escondido dentro de um componente.
 */
export const PARAMS: readonly Param[] = [
  // Geracao
  {
    id: 'cana_moida_sp',
    grupo: 'geracao',
    rotulo: 'Cana moída em São Paulo',
    explicacao: 'Quanto de cana as usinas paulistas processam por safra.',
    unidade: 'Mt',
    padrao: { real: 439.1, ideal: 439.1 },
    min: 300,
    max: 550,
    passo: 1,
    fontes: ['atlas2020', 'pam2023'],
    nota: 'Produção de SP. A base do CP2B atende 247,2 Mt (56,3%); a diferença fica com usinas não mapeadas.',
  },
  {
    id: 'bagaco_rpr',
    grupo: 'geracao',
    rotulo: 'Bagaço gerado',
    explicacao: 'Bagaço úmido que sobra da moagem, por tonelada de cana.',
    unidade: 'kg_por_t',
    padrao: { real: 280, ideal: 280 },
    min: 250,
    max: 300,
    passo: 5,
    fontes: ['feedstocks_yaml'],
    nota: 'RPR de 0,25 a 0,30 t/t. O bagaço sai da moagem com cerca de 50% de umidade.',
  },
  {
    id: 'palha_gerada',
    grupo: 'geracao',
    rotulo: 'Palha gerada',
    explicacao: 'Palhiço deixado no campo pela colheita mecanizada, por tonelada de cana.',
    unidade: 'kg_por_t',
    padrao: { real: 140, ideal: 140 },
    min: 100,
    max: 180,
    passo: 5,
    fontes: ['atlas2020_p65'],
    nota: 'Base seca. Com a colheita mecanizada em mais de 96% da área de SP, a palha deixou de ser queimada e virou um estoque disponível no campo.',
  },
  {
    id: 'torta_gerada',
    grupo: 'geracao',
    rotulo: 'Torta de filtro gerada',
    explicacao: 'Torta úmida retirada na filtração do caldo, por tonelada de cana.',
    unidade: 'kg_por_t',
    padrao: { real: 35, ideal: 35 },
    min: 28,
    max: 40,
    passo: 1,
    fontes: ['atlas2020_p66'],
    nota: 'As fontes do CP2B divergem: a planilha de fatores diz 3 a 4 kg/t, o banco diz 30 a 40. O script do Atlas usa 35, adotado aqui.',
  },
  {
    id: 'etanol_por_cana',
    grupo: 'geracao',
    rotulo: 'Etanol produzido',
    explicacao: 'Etanol obtido por tonelada de cana, na média das usinas paulistas.',
    unidade: 'm3_por_t',
    padrao: { real: 0.047838, ideal: 0.047838 },
    min: 0.03,
    max: 0.07,
    passo: 0.001,
    fontes: ['atlas2020_tab_iv2'],
    nota: 'Média de usina mista. Uma usina dedicada a etanol chega perto de 0,085 m³/t.',
  },

  // Disponibilidade
  {
    id: 'incluir_bagaco',
    grupo: 'disponibilidade',
    rotulo: 'Contar bagaço como disponível para biogás',
    explicacao:
      'O padrão é não contar: o bagaço já é queimado nas caldeiras e gera 21.218 GWh/ano de bioeletricidade. Ligue para ver quanto o potencial incha se ele fosse desviado.',
    unidade: 'adimensional',
    padrao: { real: 0, ideal: 0 },
    min: 0,
    max: 1,
    passo: 1,
    booleano: true,
    fontes: ['atlas2020_p65', 'unica2024'],
    nota: 'Contá-lo duplicaria energia que o setor já recupera. Usar o bagaço como proxy da cana foi o maior erro corrigido do projeto.',
  },
  {
    id: 'bagaco_excedente',
    grupo: 'disponibilidade',
    rotulo: 'Bagaço excedente à cogeração',
    explicacao: 'Fração do bagaço que sobraria depois de atender a demanda de vapor da usina.',
    unidade: 'fracao',
    padrao: { real: 0.1818, ideal: 0.22 },
    min: 0,
    max: 0.4,
    passo: 0.01,
    fontes: ['feedstocks_yaml', 'residuos_cp2b'],
    nota: 'Só entra na conta se a chave do bagaço estiver ligada.',
  },
  {
    id: 'palha_recolhivel',
    grupo: 'disponibilidade',
    rotulo: 'Palha recolhível',
    explicacao: 'Fração da palha que pode sair do campo sem comprometer o solo.',
    unidade: 'fracao',
    padrao: { real: 0.4, ideal: 0.5 },
    min: 0,
    max: 0.7,
    passo: 0.05,
    fontes: ['atlas2020_p65', 'carvalho2017', 'tenelli2021'],
    nota: 'De 50 a 60% precisa ficar como cobertura, contra erosão e perda de água. O recolhimento custa cerca de R$ 65 por tonelada.',
  },
  {
    id: 'torta_disponivel',
    grupo: 'disponibilidade',
    rotulo: 'Torta disponível',
    explicacao:
      'Fração da torta que chega ao biodigestor em vez de ir direto ao campo como adubo.',
    unidade: 'fracao',
    padrao: { real: 1.0, ideal: 1.0 },
    min: 0,
    max: 1,
    passo: 0.05,
    fontes: ['atlas2020_p66'],
    nota: 'O ramo do Atlas não aplica desconto: digerir a torta não impede o uso agrícola, porque o digestato mantém P, K e Ca e volta ao campo.',
  },
  {
    id: 'vinhaca_disponivel',
    grupo: 'disponibilidade',
    rotulo: 'Vinhaça disponível',
    explicacao: 'Fração da vinhaça que passa por biodigestão antes da fertirrigação.',
    unidade: 'fracao',
    padrao: { real: 1.0, ideal: 1.0 },
    min: 0,
    max: 1,
    passo: 0.05,
    fontes: ['atlas2020_p67', 'cetesb_p4231'],
    nota: 'A fertirrigação é obrigatória (CETESB P4.231) mas não compete com a digestão: as duas são sequenciais, o digestato volta ao canavial.',
  },
  {
    id: 'perda_estocagem_palha',
    grupo: 'disponibilidade',
    rotulo: 'Perda de estocagem da palha',
    explicacao:
      'Perda por deterioração entre a safra e o uso. A metodologia publicada assume zero; este controle existe para você testar o efeito.',
    unidade: 'fracao',
    padrao: { real: 0, ideal: 0 },
    min: 0,
    max: 0.3,
    passo: 0.01,
    fontes: ['fde_methodology'],
    nota: 'Limitação declarada pela própria metodologia: sem penalidade de armazenamento, a disponibilidade da palha sazonal pode estar superestimada.',
  },

  // Conversao
  {
    id: 'bmp_bagaco',
    grupo: 'conversao',
    rotulo: 'BMP do bagaço',
    explicacao: 'Metano gerado por quilo de sólidos voláteis do bagaço.',
    unidade: 'LCH4_por_kgSV',
    padrao: { real: 165, ideal: 165 },
    min: 115,
    max: 220,
    passo: 5,
    fontes: ['paulose2021', 'talha2016'],
    nota: 'Sem pré-tratamento fica na faixa baixa; com explosão a vapor chega a 218.',
  },
  {
    id: 'bmp_palha',
    grupo: 'conversao',
    rotulo: 'BMP da palha',
    explicacao: 'Metano gerado por quilo de sólidos voláteis da palha.',
    unidade: 'LCH4_por_kgSV',
    padrao: { real: 175, ideal: 175 },
    min: 140,
    max: 250,
    passo: 5,
    fontes: ['paulose2021', 'velasquez2020'],
    nota: 'Relação C/N alta, entre 75 e 100 — pede co-digestão para equilibrar.',
  },
  {
    id: 'bmp_torta',
    grupo: 'conversao',
    rotulo: 'BMP da torta de filtro',
    explicacao: 'Metano gerado por quilo de sólidos voláteis da torta.',
    unidade: 'LCH4_por_kgSV',
    padrao: { real: 280, ideal: 280 },
    min: 200,
    max: 380,
    passo: 10,
    fontes: ['talha2016', 'velasquez2020'],
    nota: 'O melhor BMP da cana. Rica em matéria orgânica e nutrientes.',
  },
  {
    id: 'sv_bagaco',
    grupo: 'conversao',
    rotulo: 'Sólidos voláteis do bagaço',
    explicacao: 'Fração do bagaço úmido que é matéria orgânica digerível.',
    unidade: 'percent',
    padrao: { real: 53, ideal: 53 },
    min: 40,
    max: 65,
    passo: 1,
    fontes: ['feedstocks_yaml'],
    nota: 'Sólidos totais 58,9% multiplicados por voláteis 90% dos sólidos.',
  },
  {
    id: 'sv_palha',
    grupo: 'conversao',
    rotulo: 'Sólidos voláteis da palha',
    explicacao: 'Fração da palha úmida que é matéria orgânica digerível.',
    unidade: 'percent',
    padrao: { real: 56, ideal: 56 },
    min: 40,
    max: 75,
    passo: 1,
    fontes: ['atlas2020', 'feedstocks_yaml'],
    nota: 'Base úmida, como usa o script do Atlas.',
  },
  {
    id: 'sv_torta',
    grupo: 'conversao',
    rotulo: 'Sólidos voláteis da torta',
    explicacao: 'Fração da torta úmida que é matéria orgânica digerível.',
    unidade: 'percent',
    padrao: { real: 20, ideal: 20 },
    min: 12,
    max: 32,
    passo: 1,
    fontes: ['atlas2020', 'feedstocks_yaml'],
    nota: 'Base úmida. A torta sai da filtração com 75 a 85% de umidade.',
  },
  {
    id: 'vinhaca_biogas',
    grupo: 'conversao',
    rotulo: 'Biogás da vinhaça',
    explicacao: 'Biogás gerado por metro cúbico de etanol destilado.',
    unidade: 'm3Biogas_por_m3',
    padrao: { real: 114, ideal: 114 },
    min: 80,
    max: 150,
    passo: 2,
    fontes: ['atlas2020_p67'],
    nota: 'Rota direta do Atlas: não passa por BMP nem por sólidos voláteis, vai do volume de etanol direto ao biogás.',
  },
  {
    id: 'ch4_vinhaca',
    grupo: 'conversao',
    rotulo: 'Teor de CH₄ na vinhaça',
    explicacao: 'Concentração de metano no biogás da vinhaça.',
    unidade: 'fracao',
    padrao: { real: 0.5, ideal: 0.65 },
    min: 0.4,
    max: 0.7,
    passo: 0.01,
    fontes: ['atlas2020_p67'],
    nota: 'A diferença entre Real e Ideal aqui é de operação do reator, não de disponibilidade da matéria-prima.',
  },

  // Energia
  {
    id: 'fracao_ch4_biogas',
    grupo: 'energia',
    rotulo: 'CH₄ no biogás',
    explicacao: 'Concentração média de metano usada para converter entre CH₄ e biogás bruto.',
    unidade: 'fracao',
    padrao: { real: 0.625, ideal: 0.625 },
    min: 0.5,
    max: 0.7,
    passo: 0.005,
    fontes: ['fiesp2025'],
    nota: 'Biogás é CH₄ dividido por este valor. Nunca some volume de metano com volume de biogás.',
  },
  {
    id: 'pci_ch4',
    grupo: 'energia',
    rotulo: 'Poder calorífico do CH₄',
    explicacao: 'Energia térmica contida em um metro cúbico normal de metano.',
    unidade: 'kWh_por_m3',
    padrao: { real: 9.94, ideal: 9.94 },
    min: 9.5,
    max: 10,
    passo: 0.01,
    fontes: ['bueno2016'],
    nota: 'O Atlas usa 9,97; a diferença é irrelevante na escala estadual.',
  },
  {
    id: 'eficiencia_eletrica',
    grupo: 'energia',
    rotulo: 'Eficiência elétrica',
    explicacao: 'Fração da energia térmica que vira eletricidade num motogerador.',
    unidade: 'fracao',
    padrao: { real: 0.38, ideal: 0.38 },
    min: 0.3,
    max: 0.45,
    passo: 0.01,
    fontes: ['abiogas2018'],
    nota: 'Motor de ciclo Otto a biogás. Turbinas e células a combustível ficam fora desta faixa.',
  },
  {
    id: 'rendimento_upgrading',
    grupo: 'energia',
    rotulo: 'Rendimento do upgrading',
    explicacao: 'Fração do metano que sobrevive à purificação para virar biometano.',
    unidade: 'fracao',
    padrao: { real: 0.97, ideal: 0.98 },
    min: 0.9,
    max: 0.995,
    passo: 0.005,
    fontes: ['abiogas2018'],
    nota: 'Membrana e PSA ficam entre 96 e 99%. A perda é o metano que escapa no gás residual.',
  },

  // Economia
  {
    id: 'preco_eletricidade',
    grupo: 'economia',
    rotulo: 'Preço da eletricidade',
    explicacao: 'Tarifa de referência para energia exportada à rede.',
    unidade: 'BRL',
    padrao: { real: 0.68, ideal: 0.68 },
    min: 0.3,
    max: 1.2,
    passo: 0.01,
    fontes: ['cpfl2025'],
  },
  {
    id: 'preco_biometano',
    grupo: 'economia',
    rotulo: 'Preço do biometano',
    explicacao: 'Preço de referência do metro cúbico de biometano.',
    unidade: 'BRL',
    padrao: { real: 3.0, ideal: 3.0 },
    min: 1.5,
    max: 6,
    passo: 0.1,
    fontes: ['comgas2025'],
  },
  {
    id: 'preco_carbono',
    grupo: 'economia',
    rotulo: 'Preço do carbono',
    explicacao: 'Valor de referência da tonelada de CO₂ equivalente evitada.',
    unidade: 'BRL',
    padrao: { real: 50, ideal: 50 },
    min: 0,
    max: 400,
    passo: 5,
    fontes: ['market_prices'],
    nota: 'Mercado voluntário brasileiro. O mercado regulado europeu opera muito acima disso.',
  },
]

const POR_ID = new Map<ParamId, Param>(PARAMS.map((p) => [p.id, p]))

export function getParam(id: ParamId): Param {
  const p = POR_ID.get(id)
  if (!p) throw new Error(`Parametro desconhecido: ${id}`)
  return p
}

export function paramsDoPreset(preset: PresetId): ParamSet {
  return Object.fromEntries(PARAMS.map((p) => [p.id, p.padrao[preset]]))
}

/** Ids cujo valor atual difere do padrao do preset. */
export function desviosDoPreset(atual: ParamSet, preset: PresetId): ParamId[] {
  return PARAMS.filter((p) => {
    const v = atual[p.id]
    return v !== undefined && Math.abs(v - p.padrao[preset]) > 1e-9
  }).map((p) => p.id)
}
